FROM ubuntu 18.04

MAINTAINER aditya <aditya98482@gmail.com>

RUN apt-get update

Run the terminal 
docker build -t myfirstimage . or docker build -t projectname <path>

RUN apt-get install git maven -Y

RUN cd /opt/ && https://downloads.apache.org/tomcat/tomcat-10/v10.0.2/bin/apache-tomcat-10.0.2.tar.gz

RUN cd /opt/ tar -xvf apache-tomcat-10.0.2.tar.gz

RUN echo "hello world" >> /opt/hello_world.py

WORKDIR /home/

EXPOSE 9090

COPY test /opt/

creat the file

ADD url /home/